# Generated by Django 5.2.11 on 2026-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'ลูกค้า'), ('STAFF', 'พนักงานขาย'), ('ADMIN', 'ผู้ดูแลระบบ')], default='CUSTOMER', max_length=20, verbose_name='บทบาท'),
        ),
    ]
