# Generated by Django 5.2.11 on 2026-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'เก็บเงินปลายทาง'), ('TRANSFER', 'โอนเงิน'), ('ONLINE', 'ชำระเงินผ่าน QR Code')], max_length=20),
        ),
    ]
