# Generated by Django 5.2.12 on 2026-03-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_stock_deducted_orderitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'เก็บเงินปลายทาง'), ('ONLINE', 'ชำระเงินผ่าน QR Code')], max_length=20),
        ),
    ]
