# Generated by Django 5.2.12 on 2026-03-25 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
