# Generated by Django 6.0.2 on 2026-02-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='รูปหมวดหมู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='จำนวนสต็อก')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปสินค้า')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-created_at'],
            },
        ),
    ]
